### ISSUE TITLE
Use 308 instead of 301, 307 instead of 302

### ISSUE THREAD

**Issue by scegg** [SecretNest/ShortUrl#3]
Try to change to use 308 instead of 301 when making a permanent redirect, use 307 instead of 302 when making a normal redirect.

UI: Checking all texts with 301 and change into 308, 302 to 307.
Code: Change all code using 301 to 308, 302 to 307.

These will keep the same verb after redirecting.

**Comment by scegg** [comment]
Code fixed.
https://github.com/SecretNest/ShortUrl/commit/533968ca00217b3a32214286f88d595c83a42e0b

**Comment by sgjsakura** [comment]
UI Updated
